# Generated by Django 5.1.1 on 2024-11-17 02:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('payment_method', models.CharField(choices=[('card', 'Картка'), ('paypal', 'PayPal'), ('cash', 'Готівка')], max_length=50, verbose_name='Метод оплати')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час платежу')),
                ('status', models.CharField(choices=[('pending', 'Очікується'), ('completed', 'Завершено'), ('failed', 'Неуспішно')], default='pending', max_length=20, verbose_name='Статус')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID транзакції')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
    ]
