# Generated by Django 5.1.1 on 2024-11-18 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True, verbose_name='Трек-номер')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вага')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status', models.CharField(choices=[('pending', 'Очікує відправки'), ('in_sorting_center', 'У сортувальному центрі'), ('in_transit', 'В дорозі'), ('ready_for_pickup', 'Готова до отримання'), ('delivered', 'Доставлено')], default='Очікування', max_length=50, verbose_name='Статус')),
                ('redirected', models.BooleanField(default=False, verbose_name='Переадресовано')),
                ('redirect_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Нова адреса доставки')),
                ('current_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поточне місцезнаходження')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('is_received', models.BooleanField(default=False, verbose_name='Отримано')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплати')),
                ('hidden_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата приховування')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_parcels', to=settings.AUTH_USER_MODEL, verbose_name='Отримувач')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_parcels', to=settings.AUTH_USER_MODEL, verbose_name='Відправник')),
            ],
        ),
    ]
