# Generated by Django 5.1.1 on 2024-10-17 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=255, verbose_name="Ім'я отримувача")),
                ('recipient_address', models.TextField(verbose_name='Адреса отримувача')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email отримувача')),
                ('tracking_number', models.CharField(max_length=20, unique=True, verbose_name='Трек-номер')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вага (кг)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_parcels', to=settings.AUTH_USER_MODEL, verbose_name='Відправник')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оновлення')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='parcels.parcel', verbose_name='Посилка')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
