# Generated by Django 5.1.1 on 2024-11-16 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='recipient_address',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='recipient_email',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='recipient_name',
        ),
        migrations.AddField(
            model_name='parcel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_parcels', to=settings.AUTH_USER_MODEL, verbose_name='Отримувач'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='status',
            field=models.CharField(default='Очікує відправки', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Трек-номер'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вага'),
        ),
        migrations.DeleteModel(
            name='ParcelStatus',
        ),
    ]
