# Generated by Django 5.1.1 on 2024-11-16 14:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_remove_parcel_recipient_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='id',
        ),
        migrations.AlterField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Трек-номер'),
        ),
    ]
