# Generated by Django 5.1.1 on 2024-11-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_parcel_hidden_at_parcel_is_paid_parcel_is_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує відправки'), ('in_sorting_center', 'У сортувальному центрі'), ('in_transit', 'В дорозі'), ('ready_for_pickup', 'Готова до отримання'), ('delivered', 'Доставлено')], default='Очікування', max_length=50, verbose_name='Статус'),
        ),
    ]
