# Generated by Django 5.1.1 on 2024-11-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_remove_parcel_id_alter_parcel_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує відправки'), ('in_sorting_center', 'У сортувальному центрі'), ('in_transit', 'В дорозі'), ('delivered', 'Доставлено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
