# Generated by Django 5.1.1 on 2024-11-16 15:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_alter_parcel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
